name: finance_ai
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  camera: ^0.11.0+2
  cloud_firestore: ^5.5.1
  dotted_border: ^2.1.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_mlkit_commons: ^0.9.0
  google_mlkit_text_recognition: ^0.14.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  langchain: ^0.7.4
  langchain_openai: ^0.7.0
  logging: ^1.2.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"

  android: "launcher_icon"
  min_sdk_android: 21

  ios: true
  remove_alpha_channel_ios: true

flutter_native_splash:
  color: "#7F3DFF"
  image: assets/financeai.png
  color_dark: "#7F3DFF"
  image_dark: assets/financeai.png

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
